FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY audit.py .

# Команда запуска uvicorn на всех интерфейсах 0.0.0.0:8000
CMD ["uvicorn", "audit:app", "--host", "0.0.0.0", "--port", "8000"]